[workspace]
members = [".", "components/*"]
default-members = ["."]

[workspace.dependencies]
getset = "0.1.6"
serde = { version = "1.0.228", features = ["derive"] }
snafu = "0.9.0"
tempfile = "3"
toml = "1.1.2"


[package]
name = "webclassic"
version = "0.1.0"
edition = "2024"

[dependencies]

webclassic-handler-core = { path = "components/webclassic-handler-core" }
webclassic-handler-static = { path = "components/webclassic-handler-static" }
webclassic-http = { path = "components/webclassic-http" }
webclassic-runtime = { path = "components/webclassic-runtime" }
webclassic-service = { path = "components/webclassic-service" }
webclassic-web = { path = "components/webclassic-web" }
