listen = "127.0.0.1:8080"
max_connections = 32
max_pending = 128

[content]
root = "./www"
index = "index.html"

[[cgi]]
methods = ["GET"]
prefix = "/cgi-bin/env"
script = "./www/cgi-bin/env"

[[cgi]]
methods = ["GET"]
prefix = "/cgi-bin/time"
interpreter = "/bin/sh"
script = "./www/cgi-bin/time"

[error_pages]
"404" = "404.html"
